import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml",
]

[font.normal]
family = "0xProto Nerd Font"

[env]
TERM = "xterm-256color"
